name: C Project CI with Python Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind
          pip install norminette

      - name: Run Norminette check
        run: norminette ./ || (echo "Norminette check failed. Please fix coding style issues." && exit 1)

      - name: Build project with Make
        run: make re

      - name: Run e2e tests and performance checks
        run: |
          chmod +x test/simple-test.sh && ./test/simple-test.sh
          chmod +x test/performance-test.sh && ./test/performance-test.sh
          python3 test/test_performance.py
          python3 test/test_positive.py

      - name: Run Valgrind memory check
        run: |
          echo -e "apple\nblue\nbanana\nyellow\napple\nred\n\napple\nbanana\nnonexistent" > valgrind_input.txt

          valgrind \
            --leak-check=full \
            --show-leak-kinds=all \
            --track-origins=yes \
            --log-file="valgrind-out.txt" \
            ./hotrace < valgrind_input.txt

          echo "--- Valgrind Output ---"
          cat valgrind-out.txt
          echo "-----------------------"

          if ! grep -q "All heap blocks were freed -- no leaks are possible" valgrind-out.txt; then
            echo "Valgrind detected memory leaks."
            exit 1
          fi
          
          echo "Valgrind check passed: No memory leaks detected."
